export function buildArtifacts(scan, analysis) {
  return {
    "AGENT_ACTIONS.md": renderAgentActions(scan, analysis),
    "SKILL.md": renderSkill(scan, analysis),
    "mcp-server.js": renderMcpServer(scan, analysis),
    "orbit.mcp.json": renderMcpManifest(scan, analysis),
    "openapi.json": renderOpenApi(scan, analysis),
    "bazaar-resource.json": renderBazaarResource(scan, analysis),
    "mcp-readiness.json": renderReadinessJson(scan, analysis),
  };
}

function renderAgentActions(scan, analysis) {
  const lines = [
    `# ${scan.projectName} Agent Actions`,
    "",
    `Readiness score: ${analysis.scorecard.score}/100 (${analysis.scorecard.status})`,
    "",
    "## Candidate actions",
    "",
  ];

  for (const action of analysis.actions) {
    lines.push(`- ${action.name}`);
    lines.push(`  - Route: \`${action.method} ${action.path}\``);
    lines.push(`  - Risk: \`${action.risk}\``);
    lines.push(`  - Auth: \`${action.auth}\``);
    lines.push(`  - Human confirmation: \`${action.confirmation ? "required" : "not required by default"}\``);
    lines.push(`  - Signing required: \`${action.signing ? "likely" : "no"}\``);
    lines.push(`  - Payment: \`${action.payment}\``);
    lines.push(`  - Source: \`${action.source}\``);
  }

  lines.push("");
  lines.push("## Risks");
  lines.push("");
  for (const risk of analysis.risks) {
    lines.push(`- ${risk}`);
  }
  if (!analysis.risks.length) {
    lines.push("- No major readiness risks detected from static scan.");
  }

  return lines.join("\n");
}

function renderSkill(scan, analysis) {
  const readOnly = analysis.actions.find((action) => action.risk === "read-only");
  const primary = analysis.actions[0];
  const lines = [
    "---",
    `name: ${sanitizeName(scan.projectName)}`,
    `description: Agent-ready wrapper for ${scan.projectName}. Generated by echo-orbit.`,
    "---",
    "",
    `# ${scan.projectName}`,
    "",
    `This skill was generated from a static repo scan of \`${scan.projectName}\`. Review the routes and risks before publishing.`,
    "",
    "## Suggested entrypoints",
    "",
    `- Primary action: \`${primary.name}\` via \`${primary.method} ${primary.path}\``,
    `- Safe starting action: \`${readOnly ? `${readOnly.method} ${readOnly.path}` : "manual review required"}\``,
    "",
    "## Agent guidance",
    "",
    "- Prefer read-only routes first.",
    "- Require human confirmation before wallet-signing or destructive routes.",
    "- Surface payment requirements before attempting paid routes.",
    "- Use the generated OpenAPI and Bazaar resource files as review drafts, not final legal/security guarantees.",
    "- Use the generated MCP server as a local adapter after setting ORBIT_TARGET_BASE_URL.",
    "- Keep outputs concise and include route/method in receipts or logs.",
    "",
    "## Action inventory",
    "",
  ];

  for (const action of analysis.actions) {
    lines.push(`- \`${action.method} ${action.path}\` — ${action.risk}, auth=${action.auth}, payment=${action.payment}, signing=${action.signing ? "likely" : "no"}`);
  }

  return lines.join("\n");
}

function renderMcpServer(scan, analysis) {
  const actions = analysis.actions
    .filter((action) => action.method !== "MANUAL" && action.path !== "n/a")
    .map((action) => ({
      id: action.id,
      name: action.name,
      method: action.method,
      path: action.path,
      risk: action.risk,
      auth: action.auth,
      payment: action.payment,
      signing: action.signing,
      confirmation: action.confirmation,
      inputSchema: buildMcpInputSchema(action),
    }));

  return `#!/usr/bin/env node
// Generated by echo-orbit for ${escapeComment(scan.projectName)}.
// Set ORBIT_TARGET_BASE_URL to the app/API base URL before running.

const actions = ${JSON.stringify(actions, null, 2)};
const targetBaseUrl = process.env.ORBIT_TARGET_BASE_URL;
const allowUnconfirmed = process.env.ORBIT_ALLOW_UNCONFIRMED === "1";
const timeoutMs = Number(process.env.ORBIT_TIMEOUT_MS ?? 30000);
const maxResponseBytes = Number(process.env.ORBIT_MAX_RESPONSE_BYTES ?? 1000000);
let buffer = "";

process.stdin.setEncoding("utf8");
process.stdin.on("data", (chunk) => {
  buffer += chunk;
  let newlineIndex = buffer.indexOf("\\n");
  while (newlineIndex !== -1) {
    const line = buffer.slice(0, newlineIndex).trim();
    buffer = buffer.slice(newlineIndex + 1);
    if (line) handleLine(line);
    newlineIndex = buffer.indexOf("\\n");
  }
});

async function handleLine(line) {
  let request;
  try {
    request = JSON.parse(line);
  } catch (error) {
    sendError(null, -32700, "Parse error");
    return;
  }

  try {
    if (request.method === "initialize") {
      sendResult(request.id, {
        protocolVersion: "2024-11-05",
        capabilities: { tools: {} },
        serverInfo: { name: "${escapeString(sanitizeName(scan.projectName))}-orbit", version: "${escapeString(scan.packageJson?.version ?? "0.0.0")}" }
      });
      return;
    }

    if (request.method === "notifications/initialized") {
      return;
    }

    if (request.method === "tools/list") {
      sendResult(request.id, {
        tools: actions.map((action) => ({
          name: action.id,
          description: describeAction(action),
          inputSchema: action.inputSchema,
          annotations: {
            title: action.name,
            readOnlyHint: action.risk === "read-only",
            destructiveHint: action.risk === "destructive",
            openWorldHint: true
          },
          _meta: {
            "echo-orbit/risk": action.risk,
            "echo-orbit/auth": action.auth,
            "echo-orbit/payment": action.payment,
            "echo-orbit/walletSigning": action.signing,
            "echo-orbit/humanConfirmation": action.confirmation
          }
        }))
      });
      return;
    }

    if (request.method === "tools/call") {
      const name = request.params?.name;
      const args = request.params?.arguments ?? {};
      const action = actions.find((candidate) => candidate.id === name);
      if (!action) {
        sendError(request.id, -32602, \`Unknown tool: \${name}\`);
        return;
      }
      const result = await callAction(action, args);
      sendResult(request.id, {
        content: [
          {
            type: "text",
            text: JSON.stringify(result, null, 2)
          }
        ]
      });
      return;
    }

    sendError(request.id, -32601, \`Method not found: \${request.method}\`);
  } catch (error) {
    sendError(request.id, -32000, error instanceof Error ? error.message : String(error));
  }
}

async function callAction(action, args) {
  if (!targetBaseUrl) {
    throw new Error("ORBIT_TARGET_BASE_URL is required before calling app tools");
  }
  if (action.confirmation && !allowUnconfirmed && args.confirm !== true) {
    throw new Error(\`Human confirmation required for \${action.id}. Call again with confirm: true after user approval.\`);
  }

  const pathParams = args.pathParams ?? {};
  const query = args.query ?? {};
  const body = args.body ?? {};
  let path = action.path.replace(/:([A-Za-z0-9_]+)/g, (_, key) => {
    if (pathParams[key] == null) throw new Error(\`Missing path param: \${key}\`);
    return encodeURIComponent(String(pathParams[key]));
  });

  const url = new URL(path, targetBaseUrl);
  for (const [key, value] of Object.entries(query)) {
    if (value == null) continue;
    url.searchParams.set(key, String(value));
  }

  const headers = { accept: "application/json" };
  if (process.env.ORBIT_API_KEY) {
    headers.authorization = \`Bearer \${process.env.ORBIT_API_KEY}\`;
  }
  if (args.headers && typeof args.headers === "object") {
    for (const [key, value] of Object.entries(args.headers)) {
      if (value != null) headers[key] = String(value);
    }
  }

  const init = { method: action.method, headers };
  const abort = new AbortController();
  const timeout = setTimeout(() => abort.abort(), timeoutMs);
  init.signal = abort.signal;
  if (["POST", "PUT", "PATCH", "DELETE"].includes(action.method) && Object.keys(body).length > 0) {
    headers["content-type"] = "application/json";
    init.body = JSON.stringify(body);
  }

  let response;
  let text;
  try {
    response = await fetch(url, init);
    text = await readLimitedText(response, maxResponseBytes);
  } finally {
    clearTimeout(timeout);
  }
  const payload = parseMaybeJson(text);

  return {
    ok: response.ok,
    status: response.status,
    method: action.method,
    path: action.path,
    risk: action.risk,
    payment: action.payment,
    data: payload
  };
}

async function readLimitedText(response, maxBytes) {
  const text = await response.text();
  if (Buffer.byteLength(text, "utf8") > maxBytes) {
    throw new Error(\`Target response exceeded ORBIT_MAX_RESPONSE_BYTES=\${maxBytes}\`);
  }
  return text;
}

function parseMaybeJson(text) {
  try {
    return text ? JSON.parse(text) : null;
  } catch {
    return text;
  }
}

function describeAction(action) {
  const bits = [
    \`\${action.name} (\${action.method} \${action.path})\`,
    \`risk=\${action.risk}\`,
    \`auth=\${action.auth}\`,
    \`payment=\${action.payment}\`
  ];
  if (action.signing) bits.push("wallet-signing=likely");
  if (action.confirmation) bits.push("human-confirmation=required");
  return bits.join("; ");
}

function sendResult(id, result) {
  process.stdout.write(JSON.stringify({ jsonrpc: "2.0", id, result }) + "\\n");
}

function sendError(id, code, message) {
  process.stdout.write(JSON.stringify({ jsonrpc: "2.0", id, error: { code, message } }) + "\\n");
}
`;
}

function renderMcpManifest(scan, analysis) {
  return JSON.stringify({
    name: sanitizeName(scan.projectName),
    displayName: `${scan.projectName} Orbit MCP Adapter`,
    version: scan.packageJson?.version ?? "0.0.0",
    generatedBy: "echo-orbit",
    description: scan.packageJson?.description ?? `Generated MCP adapter for ${scan.projectName}.`,
    command: "node",
    args: ["./mcp-server.js"],
    env: {
      ORBIT_TARGET_BASE_URL: {
        description: "Base URL for the app/API being adapted.",
        required: true,
      },
      ORBIT_API_KEY: {
        description: "Optional bearer token sent to the target app.",
        required: false,
      },
      ORBIT_ALLOW_UNCONFIRMED: {
        description: "Set to 1 only when a human has approved dangerous tools.",
        required: false,
      },
      ORBIT_TIMEOUT_MS: {
        description: "Per-call timeout for forwarded app requests. Defaults to 30000.",
        required: false,
      },
      ORBIT_MAX_RESPONSE_BYTES: {
        description: "Maximum response body size before the adapter aborts. Defaults to 1000000.",
        required: false,
      },
    },
    readiness: {
      score: analysis.scorecard.score,
      status: analysis.scorecard.status,
    },
    tools: analysis.actions
      .filter((action) => action.method !== "MANUAL" && action.path !== "n/a")
      .map((action) => ({
        name: action.id,
        title: action.name,
        method: action.method,
        path: action.path,
        risk: action.risk,
        auth: action.auth,
        payment: action.payment,
        walletSigning: action.signing,
        humanConfirmation: action.confirmation,
      })),
  }, null, 2);
}

function renderOpenApi(scan, analysis) {
  const paths = {};
  for (const action of analysis.actions) {
    if (action.method === "MANUAL" || action.path === "n/a") continue;
    const path = toOpenApiPath(action.path);
    paths[path] ??= {};
    paths[path][action.method.toLowerCase()] = {
      operationId: action.id,
      summary: action.name,
      description: [
        `Generated by echo-orbit from ${action.source}.`,
        `Risk: ${action.risk}.`,
        `Auth: ${action.auth}.`,
        `Payment: ${action.payment}.`,
        action.confirmation ? "Human confirmation should be required before execution." : "Safe for agent preflight by default.",
      ].join(" "),
      tags: [action.risk],
      parameters: buildPathParameters(action.path),
      ...buildRequestBody(action),
      responses: {
        "200": {
          description: "Successful response",
          content: {
            "application/json": {
              schema: genericObjectSchema("response"),
            },
          },
        },
        "400": {
          description: "Invalid request",
        },
        "401": {
          description: "Authentication required",
        },
        "402": {
          description: "Payment required",
        },
      },
      "x-agent-risk": action.risk,
      "x-agent-auth": action.auth,
      "x-agent-payment": action.payment,
      "x-human-confirmation": action.confirmation,
      "x-wallet-signing": action.signing,
    };
  }

  return JSON.stringify({
    openapi: "3.1.0",
    info: {
      title: `${scan.projectName} Agent API`,
      version: scan.packageJson?.version ?? "0.0.0",
      description: "Draft agent-facing API contract generated by echo-orbit. Review before publishing.",
    },
    servers: [
      {
        url: "https://example.com",
        description: "Replace with the production API base URL before publishing.",
      },
    ],
    paths,
    components: {
      schemas: {
        AgentActionRequest: genericObjectSchema("request"),
        AgentActionResponse: genericObjectSchema("response"),
      },
    },
  }, null, 2);
}

function renderBazaarResource(scan, analysis) {
  const safeActions = analysis.actions.filter((action) => action.risk === "read-only");
  const paidActions = analysis.actions.filter((action) => action.payment !== "none");
  return JSON.stringify({
    name: scan.projectName,
    version: scan.packageJson?.version ?? "0.0.0",
    description: scan.packageJson?.description ?? `Agent-ready package for ${scan.projectName}.`,
    generatedBy: "echo-orbit",
    readiness: {
      score: analysis.scorecard.score,
      status: analysis.scorecard.status,
      risks: analysis.risks,
    },
    discovery: {
      openapi: "./openapi.json",
      agentActions: "./AGENT_ACTIONS.md",
      skill: "./SKILL.md",
      readiness: "./mcp-readiness.json",
    },
    agentPolicy: {
      safeStartActionIds: safeActions.map((action) => action.id),
      requiresHumanConfirmationActionIds: analysis.actions
        .filter((action) => action.confirmation)
        .map((action) => action.id),
      walletSigningActionIds: analysis.actions
        .filter((action) => action.signing)
        .map((action) => action.id),
      paidActionIds: paidActions.map((action) => action.id),
    },
    actions: analysis.actions.map((action) => ({
      id: action.id,
      name: action.name,
      method: action.method,
      path: action.path,
      risk: action.risk,
      auth: action.auth,
      payment: action.payment,
      signing: action.signing,
      confirmation: action.confirmation,
      source: action.source,
      inputSchema: genericObjectSchema("request"),
      outputSchema: genericObjectSchema("response"),
    })),
  }, null, 2);
}

function renderReadinessJson(scan, analysis) {
  return JSON.stringify({
    project: scan.projectName,
    score: analysis.scorecard.score,
    status: analysis.scorecard.status,
    checks: analysis.scorecard.checks,
    actions: analysis.actions,
    risks: analysis.risks,
  }, null, 2);
}

function sanitizeName(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

function toOpenApiPath(path) {
  return path.replace(/:([A-Za-z0-9_]+)/g, "{$1}");
}

function buildPathParameters(path) {
  const names = Array.from(path.matchAll(/:([A-Za-z0-9_]+)/g), (match) => match[1]);
  return names.map((name) => ({
    name,
    in: "path",
    required: true,
    schema: {
      type: "string",
    },
  }));
}

function buildRequestBody(action) {
  if (!["POST", "PUT", "PATCH"].includes(action.method)) return {};
  return {
    requestBody: {
      required: action.risk !== "read-only",
      content: {
        "application/json": {
          schema: genericObjectSchema("request"),
        },
      },
    },
  };
}

function buildMcpInputSchema(action) {
  const pathParams = buildPathParameters(action.path);
  const properties = {
    pathParams: {
      type: "object",
      additionalProperties: {
        type: "string",
      },
      description: "Values for route parameters such as :id or :slug.",
    },
    query: {
      type: "object",
      additionalProperties: true,
      description: "Optional query-string parameters.",
    },
    headers: {
      type: "object",
      additionalProperties: {
        type: "string",
      },
      description: "Optional extra HTTP headers for the target app.",
    },
  };
  const required = [];

  if (["POST", "PUT", "PATCH", "DELETE"].includes(action.method)) {
    properties.body = {
      type: "object",
      additionalProperties: true,
      description: "JSON request body for the target app.",
    };
  }
  if (action.confirmation) {
    properties.confirm = {
      type: "boolean",
      const: true,
      description: "Must be true after explicit human approval.",
    };
    required.push("confirm");
  }
  if (pathParams.length) {
    properties.pathParams.properties = Object.fromEntries(pathParams.map((param) => [param.name, { type: "string" }]));
    properties.pathParams.required = pathParams.map((param) => param.name);
    required.push("pathParams");
  }

  return {
    type: "object",
    additionalProperties: false,
    properties,
    required,
  };
}

function genericObjectSchema(role) {
  return {
    type: "object",
    additionalProperties: true,
    description: `Generated placeholder ${role} schema. Replace with the exact contract before marketplace submission.`,
  };
}

function escapeString(value) {
  return String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function escapeComment(value) {
  return String(value).replace(/\*\//g, "* /");
}
